### ISSUE TITLE
Game does not complete 

### ISSUE THREAD

**Issue by thinus-potgieter** [EntelectChallenge/2020-Overdrive#49] opened 2020-04-17 14:09 UTC
Hi

See the attached screen image.   Game runs fine until round 144.   The commands appear valid, and a collision should not occur, but round 145 has both bots on x = 1499.   Bot 1 makes a valid move, but bot 2 would probably invoke the collision code.   Thereafter the position does not change irrespective of the commands issued by bot 1. 

![problem](https://user-images.githubusercontent.com/7335748/79577261-b82b1d00-80c4-11ea-81fd-1b2f2504085f.jpg)

**Comment by Jana-Wessels** [comment] 2020-05-05 18:39
Seems like the game is handeling the collision correctly according to the collision section in the rules https://github.com/EntelectChallenge/2020-Overdrive/blob/master/game-engine/game-rules.md,

Is the issue later that a winner is not chosen? 

I am closing the ticket for now but please reopen it with further information if the problem is still occurring or if I misunderstood..

**Closed by Jana-Wessels** 2020-05-05 18:39 UTC
