### ISSUE TITLE
Placing an oil block causes the player to be hit themselves

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#17] opened 2020-03-27 12:12 UTC
When using the USE_OIL command it causes the player that is placing the oil block to be hit themselves, slowing down the player and putting them in the HIT_OIL state. The following example illustrates this. While it doesn't show the oil being placed it can be seen that the speed is reduced, one oil powerup is used and that the state is now HIT_OIL. I believe this is due to the fact that the oil is placed at the player's current position rather than one block behind them (contrary to what is stated in the guide).

```
===================================================
round:37
player: id:1 position: y:2 x:339 speed:9 state:ACCELERATING boosting:false boost-counter:0 powerups: OIL:1
opponent: id:2 position: y:1 x:186 speed:3

[▓░░░░░░░░░░░░░░░░░░░░░░»░░]
[░░░░░1░░░░░░░░░░░▓░░░░░░░░]
[░░░░▓░░░░░»░░░░░▓░░░░░░░░░]
[░░░░░░░░░░░░░░░░░░░░░░░░░░]
===================================================

===================================================
round:38
player: id:1 position: y:2 x:348 speed:8 state:HIT_OIL boosting:false boost-counter:0 powerups:
opponent: id:2 position: y:2 x:188 speed:3

[░░░░░░░░░░░░░░»░░░░░░▓░░░░]
[░░░░░1░░▓░░░░░░░░░░░░░░░▓░]
[░»░░░░░▓░░░░░░░░░░░░░░░░░░]
[░░░░░░░░░░░░░░░░░▓▓░░░░▓░░]
===================================================
```

I think the problem lies in `game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/commands/UseOilCommand.scala` at line 16 -

```scala
if (carGamePlayer.hasOilItem) {
    carGamePlayer.useOilItem()
    carGameMap.applyOilToBlock(currentPlayerPosition)
}
```
Here is an example where it can be seen that the the oil is placed at the player's current position. This is from two different player's text-map logs to illustrate the issue. Here player 1 places the oil and from player 2 the oil block can later be seen:

```
===================================================
round:4
player: id:1 position: y:1 x:30 speed:9 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:1
opponent: id:2 position: y:3 x:15 speed:6

[░░▓░░1░░░░░░▓░░░░░░░░░░░░▓]
[Φ░░░░▓░▓░░░▓░░░░░░░░░░░░░░]
[░▓░░░░░░░░░░░▓░▓░░░░▓░░░░░]
[░░░░░░░░▓░░░▓░░▓░░░░░▓▓░░░]
===================================================

===================================================
round:5
player: id:2 position: y:4 x:20 speed:3 state:HIT_MUD boosting:false boost-counter:0 powerups:
opponent: id:1 position: y:1 x:39 speed:6

[░░ΦΦ░░░░░░░░▓░░█░░░░░░▓░1░]
[░░▓░▓░░▓▓░Φ░░░░▓░▓░░░▓░░░░]
[░░░░░░░░▓░░▓░░░░░░░░░░░▓░▓]
[░░░░░2░░░░░░░░░░░░▓░░░▓░░▓]
===================================================
```

**Comment by styphoiz** [comment] 2020-03-30 08:46
This seems to be the same problem when landing on Mud.

**Comment by styphoiz** [comment] 2020-03-30 15:04
Would this issue be fixed by the first round so we can get some testing in, this specific bug is significantly slowing my bot down when I initiate the USE_OIL command.

**Comment by demaniak** [comment] 2020-04-01 17:45
The problem seems to [be here](https://github.com/EntelectChallenge/2020-Overdrive/blob/e6779da7899decfb1088217b423f255b3e6f02b3/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala#L150)

Logically I would expect oil to be dropped at player.x - 1, but it is currently being dropped right smack on the player.

I'm a scale noob,but if I can get a scala plugin installed, or an scala IDE running, I'll try my hand at a PR.

**Comment by styphoiz** [comment] 2020-04-01 18:48
Does this mean landing on mud should take a hit in the next round?

**Comment by demaniak** [comment] 2020-04-01 18:51
@styphoiz that I don't know. 
Mud is part of the environment, from the start. It is supposed to be a navigation hazard for all.

Oil the player drops is added to the environment, with the intent of hindering the opponent. So it make sense that the dropper should not be penalized for using the only weapon at it's disposal. Otherwise the oil powerups are a useless feature of the game, don't you agree?

**Comment by styphoiz** [comment] 2020-04-01 19:00
I'm in agreement on the oil, just trying to understand the effect of mud, they currently both have the same behaviour because the vehicle is already on it at the start of the round.

**Comment by demaniak** [comment] 2020-04-01 20:03
Follow up to @styphoiz 's query: I'm also not 100% clear on what happens (or more accurately, what is *supposed* to happen) if you travel *through* two+ mud or oil patches. Exactly how much are you penalized in the following situations:
1. starting at speed 9 ,you travel through two mud patches, but land on empty terrain, what is your starting speed in the next round
1. starting at speed 9, you travel through one mud patch, one oil patch, but land on empty terrain, what is your starting speed in the next round
1.  all of the above, but then land on either oil or mud

As I understand things currently, that should go something like this:
1. Start next round with speed 6 (penalized twice), and score is affected
1. Start next round with speed 6 (penalized twice), and score is affected
1. well, I would sorta assume in this case, you would start with speed 3 ? (Speed 5 is just special starting speed, not available after round 1 afaik)

**Comment by Arne27** [comment] 2020-04-02 05:25
Hi @styphoiz and @demaniak.

The intended behavior for mud is that it should be dropped behind the player and not on the same block as what the player was on at that point and time. This being said it should not penalize the player dropping the oil at all.

The penalties for mud and oil should work in the same way, where you only get penalized once if you end your turn on the OIL or MUD block. 

These are both bugs that we are currently looking at and we are hoping to have a new version later today.

A quick answer to the scenarios that you pointed out.

1. _starting at speed 9 ,you travel through two mud patches, but land on empty terrain, what is your starting speed in the next round_ - Exactly like you said, you should be penalized twice and your bot should be at SPEED_STATE_@ which is 6
2. _starting at speed 9, you travel through one mud patch, one oil patch, but land on empty terrain, what is your starting speed in the next round_ - Exactly like you said, you should be penalized twice and your bot should be at SPEED_STATE_@ which is 6
3. _starting at speed 9, you travel through one mud patch, one oil patch, but then land on either oil or mud_ - 100% correct, You will start your turn on SPEED_STATE_1 which is 3. 

Thanks for your patience.

**Closed** 2020-04-03 15:30 UTC
Labels: bug
