### ISSUE TITLE
If I try to declerate at a speed of 3 after hitting a wall, I hit the wall again

### ISSUE THREAD

**Issue by ogdenm** [EntelectChallenge/2020-Overdrive#69] opened 2020-05-17 22:11 UTC
=======================================
Starting round: 136 
=======================================

======================================================================================================
round:136
player: id:2 position: y:4 x:73 speed:0 state:DECELERATING boosting:false boost-counter:0 powerups: BOOST:1
opponent: id:1 position: y:3 x:1414 speed:9

[░░░░░∱░░░░░░░▓░▓░░░░░░░▓░░]
[░░░░░░▓░░░░░░░░░░░░░░░░░░░]
[░░T░░░░░░░▓░»▓░░░░▓░░░░»░░]
[░░░░░2░░#░░░░░░░∱░░░░░░▓░░]
======================================================================================================
C;136;ACCELERATE
C;136;TURN_RIGHT
=======================================
Completed round: 136 
=======================================

=======================================
Starting round: 137 
=======================================

======================================================================================================
round:137
player: id:2 position: y:4 x:76 speed:3 state:HIT_WALL boosting:false boost-counter:0 powerups: BOOST:1
opponent: id:1 position: y:4 x:1422 speed:9

[░░∱░░░░░░░▓░▓░░░░░░░▓░░░░░]
[░░░▓░░░░░░░░░░░░░░░░░░░░░░]
[░░░░░░░▓░»▓░░░░▓░░░░»░░░░░]
[░░░░░2░░░░░░░∱░░░░░░▓░░▓░░]
======================================================================================================
C;137;DECELERATE
C;137;NOTHING
=======================================
Completed round: 137 
=======================================

=======================================
Starting round: 138 
=======================================

======================================================================================================
round:138
player: id:2 position: y:4 x:76 speed:3 state:HIT_WALL boosting:false boost-counter:0 powerups: BOOST:1
opponent: id:1 position: y:4 x:1431 speed:3

[░░∱░░░░░░░▓░▓░░░░░░░▓░░░░░]
[░░░▓░░░░░░░░░░░░░░░░░░░░░░]
[░░░░░░░▓░»▓░░░░▓░░░░»░░░░░]
[░░░░░2░░░░░░░∱░░░░░░▓░░▓░░]
======================================================================================================
C;138;DECELERATE
C;138;USE_BOOST
=======================================
Completed round: 138 
=======================================

**Comment by KyleMcAllister** [comment] 2020-05-27 18:15
Thanks @ogdenm . That definitely isn't the intended behavior We will simulate this and make adjustments if needed

**Comment by KyleMcAllister** [comment] 2020-05-29 15:16
After investigating, the state of "hit wall" makes sense since the player is still on the same block as the wall, but the speed of 3 is incorrect since decelerating from 3 should make speed 0. This will be fixed in next release

**Closed** 2020-05-31 16:06 UTC
